---
window:
  width: 15
  height: 15

data-type: real # real / integer
input: randomized # randomized / manual
fps: 2
logfile: yes
logfile-fname: bubblesort.log

with-flag: yes
neg-to-neg: yes
maximized: no
